root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/server"
  bin = "./tmp/main"
  delay = 1000
  exclude_dir = ["tmp", "vendor", ".git"]
  exclude_regex = ["_test.go"]
  exclude_unchanged = true
  follow_symlink = false
  include_ext = ["go", "tpl", "tmpl", "html", "sql"]
  kill_delay = "2s"
  send_interrupt = true
  stop_on_error = true

[log]
  time = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
